"""Content normalizer for converting raw content to ContentItem."""

from datetime import datetime

import structlog

from next_epoch.schemas.content import (
    ContentItem,
    ContentProvenance,
    Paper,
    Repository,
    FieldRef,
)
from next_epoch.schemas.enums import ContentType, SourceType

logger = structlog.get_logger()

PARSER_VERSION = "1.0.0"


def normalize_paper(paper: Paper) -> ContentItem:
    """Normalize a Paper into a ContentItem."""
    # Build provenance
    provenance = ContentProvenance(
        fetched_at=paper.created_at or datetime.utcnow(),
        fetched_from="https://arxiv.org/api/query",
        parser="arxiv_normalizer",
        parser_version=PARSER_VERSION,
        content_hash=None,  # Could hash the abstract
        language="en",  # arXiv is primarily English
    )

    return ContentItem(
        type=ContentType.PAPER,
        source=SourceType.ARXIV,
        title=paper.title,
        summary=None,  # Will be generated by summarizer
        url=paper.url,
        relevance_score=0.0,  # Will be set by scorer
        importance_score=0.0,
        novelty_score=None,
        frontier_score=None,
        tags=paper.tags,
        categories=paper.categories,  # arXiv categories map to our categories
        published_at=paper.published_at,
        processed_at=datetime.utcnow(),
        fields=[],  # Will be set by enrichment
        signals=[],  # Will be set by scorer
        provenance=provenance,
        raw_content_type="paper",
        raw_content_id=paper.id,
    )


def normalize_repository(repo: Repository) -> ContentItem:
    """Normalize a Repository into a ContentItem."""
    # Build provenance
    provenance = ContentProvenance(
        fetched_at=repo.ingested_at or datetime.utcnow(),
        fetched_from="https://github.com/trending",
        parser="github_normalizer",
        parser_version=PARSER_VERSION,
        content_hash=None,
        language=repo.language,
    )

    # Use topics as tags
    tags = list(repo.topics) if repo.topics else []

    # Add language as a tag if present
    if repo.language:
        lang_tag = repo.language.lower().replace(" ", "-")
        if lang_tag not in tags:
            tags.append(lang_tag)

    # Use first part of description as summary placeholder
    summary = repo.description[:500] if repo.description else None

    return ContentItem(
        type=ContentType.REPOSITORY,
        source=SourceType.GITHUB,
        title=f"{repo.full_name}: {repo.description[:100] if repo.description else 'GitHub Repository'}",
        summary=summary,
        url=repo.url,
        relevance_score=0.0,
        importance_score=0.0,
        novelty_score=None,
        frontier_score=None,
        tags=tags,
        categories=[],  # Will be set by enrichment
        published_at=repo.pushed_at or repo.ingested_at or datetime.utcnow(),
        processed_at=datetime.utcnow(),
        fields=[],
        signals=[],
        provenance=provenance,
        raw_content_type="repository",
        raw_content_id=repo.id,
    )


def normalize_content(raw_content: Paper | Repository) -> ContentItem:
    """Normalize any raw content type to ContentItem."""
    if isinstance(raw_content, Paper):
        return normalize_paper(raw_content)
    elif isinstance(raw_content, Repository):
        return normalize_repository(raw_content)
    else:
        raise ValueError(f"Unknown content type: {type(raw_content)}")
